const mongoose=require("mongoose");


const result_schema=mongoose.Schema({
    registration:{
        type:String,
        required:true
    },
    subject_name:{
        type:String,
        required:true
    },
    subject_number:{
        type:Number,
        required:true
    },
    bangla_number:{
        type:Number,
        default:0
    },
    english_number:{
        type:Number,
        default:0
    },
    math_number:{
        type:Number,
        default:0
    },
    science_number:{
        type:Number,
        default:0
    },
    social_number:{
        type:Number,
        default:0
    },
    islam_number:{
        type:Number,
        default:0
    },
    ict_number:{
        type:Number,
        default:0
    },
    total_number:{
        type:Number,
        default:0
    },
    exam_number:{
        type:Number,
        required:true
    },
    bangla_exam:{
        type:Number,
        default:0
    },
    english_exam:{
        type:Number,
        default:0
    },
    math_exam:{
        type:Number,
        default:0
    },
    social_exam:{
        type:Number,
        default:0
    },
    science_exam:{
        type:Number,
        default:0
    },
    ict_exam:{
        type:Number,
        default:0
    },
    islam_exam:{
        type:Number,
        default:0
    },
    date:{
        type:String,
        required:true
    }
},{timestamps:true});
const resultmodel=new mongoose.model("result",result_schema);
module.exports=resultmodel;